services:
  app:
    build: .
    container_name: formmaker_spring
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
